### ISSUE TITLE
Endpoint error

### ISSUE THREAD

**Issue by AndreaBarbon** [ncri/s3_uploader_example#10]
When I do

bundle exec rake uploader:deploy

I get the following error:

rake aborted!
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

What does it mean? What should I do to solve this?

**Comment by ncri** [comment]
I never had that myself, but a quick google for that message brings up plenty of results, e.g. http://www.digininja.org/blog/whats_in_amazons_buckets.php or http://stackoverflow.com/questions/6581502/problem-in-accessing-bucket-of-my-aws-s3-account and http://www.conandalton.net/2011/02/paperclip-s3-and-european-buckets.html
