### ISSUE TITLE
How do you display images?

### ISSUE THREAD

**Issue by frankphilips** [ncri/s3_uploader_example#11]
I got the upload working just fine to S3, but can you explain how you actually display images?

**Comment by ncri** [comment]
Maybe this helps you?

https://github.com/ncri/s3_uploader_example/pull/2

**Comment by frankphilips** [comment]
Hi,

I tried this, but when I select an image and click Ok, nothing happens. It
uploads fine with your code though. Maybe im doing something wrong.

Sent from my iPhone

On Aug 21, 2012, at 2:01 AM, Nico Ritsche notifications@github.com wrote:

Maybe this helps you?

https://github.com/ncri/s3_uploader_example/pull/2

—
Reply to this email directly or view it on
GitHubhttps://github.com/ncri/s3_uploader_example/issues/11#issuecomment-7893259.

**Comment by felipecsl** [comment]
This pull request is a bit outdated. I have to refresh my mind on it, resync and will get back to you later!

**Comment by frankphilips** [comment]
No problem, thanks!
