### ISSUE TITLE
bundle install: Could not find jquery-rails-2.0.0 in any of the sources

### ISSUE THREAD

**Issue by dpashin** [ncri/s3_uploader_example#15]
$ git clone https://github.com/ncri/s3_uploader_example.git
$ cd s3_uploader_example
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Could not find jquery-rails-2.0.0 in any of the sources

I get around this issue by recreating Gemfile.lock.

**Comment by ncri** [comment]
I don't maintain this anymore, as with Amazons new CORS feature the iframe workaround is not needed anymore: check out this instead: github.com/waynehoover/s3_direct_upload
