### ISSUE TITLE
Set file upload path as per users selection

### ISSUE THREAD

**Issue by sahil2628** [ncri/s3_uploader_example#18]
Hello,

I am a newbie.

I have cloned https://github.com/ncri/s3_uploader_example.git and made the necessary changes and it worked. 

Now I want to upload file to specific location as per user selection.

User need to select option from 
1) Dropdown: 
2) Datepicker (jQuery ui)

and fill will upload to that folder.

As per the notes The path for the uploaded files defaults to “#{controller_name}/:uuid” and can be changed in the s3_uploader helper options via the :uploaded_files_path parameter. If I make it hardcoded I can upload file to that path but what if I want to do it dynamically by users above selection.

Where do I need to change?

Can you please  tell me how can I do that?

Thanks

**Comment by ncri** [comment]
Hi there, this project is obsolete now and now longer maintained by me as there is a much simpler uploader solution now, using the recent CORS addition for Amazon S3. Check it out here: github.com/waynehoover/s3_direct_upload It's quick to setup.

**Comment by sahil2628** [comment]
Thank you so much for your quick response. My first approach was the one you suggest me(https://github.com/railscasts/383-uploading-to-amazon-s3/tree/master/gallery-jquery-fileupload). But somehow in that approach I was not able to upload file.

I got 403(Forbidden) error when I try to upload multiple files using jquery file upload.

When I try to upload single/multiple file I get alert box saying failed to upload and in console it says "Failed to load resource: the server responded with a status of 403 (Forbidden)" and "XMLHttpRequest cannot load https://xyz.s3.amazonaws.com/. Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin."

What do I need to do to fix this? 

Thanks in advance.

**Comment by ncri** [comment]
Maybe you didn't set the CORS config on your S3 bucket? Check https://github.com/waynehoover/s3_direct_upload and submit an issue there if you have trouble getting it work.

**Comment by sahil2628** [comment]
I did set the CORS config. I am able to upload file to s3 using carrierwave. But I want to upload multiple files so I am using https://github.com/railscasts/383-uploading-to-amazon-s3/tree/master/gallery-jquery-fileupload. Unfortunately I am stuck on that. 

I already posted my issue but nobody replied me so far. I hope someone can guide me to fix my issue.  

Thank you so much for your time and interest.

**Comment by ncri** [comment]
So you tried https://github.com/waynehoover/s3_direct_upload ? It handles multiple files.

**Comment by sahil2628** [comment]
I am a newbie. I didn't try https://github.com/waynehoover/s3_direct_upload.  

But yes I tried https://github.com/railscasts/383-uploading-to-amazon-s3/tree/master/gallery-jquery-fileupload. 

I guess you are also talking about the same project as in the readme it direct you to https://github.com/railscasts/383-uploading-to-amazon-s3/tree/master/gallery-jquery-fileupload

Yes I tried https://github.com/railscasts/383-uploading-to-amazon-s3/tree/master/gallery-jquery-fileupload. and not able to upload file. When I try to upload single/multiple file I get alert box saying failed to upload and in console it says "Failed to load resource: the server responded with a status of 403 (Forbidden)" and "XMLHttpRequest cannot load https://xyz.s3.amazonaws.com/. Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin."

**Comment by ncri** [comment]
That sounds like a permission issue. I recommend you try the gem i linked to a couple of times now :) I think its the easiest way of getting multiple upload to S3 working. And if you have an issue with the gem, post it in https://github.com/waynehoover/s3_direct_upload, not here.

**Comment by sahil2628** [comment]
Ok. Thanks.
