### ISSUE TITLE
Making uploads belong to other resources 

### ISSUE THREAD

**Issue by jimmytidey** [ncri/s3_uploader_example#19]
I would like to pass through the ID of a parent resource, is there an easy way to do that? I'm not sure if I can see a clean approach...

Any help much appreciated.

**Comment by ncri** [comment]
Hi Jimmy, best you switch to this gem: github.com/waynehoover/s3_direct_upload

This example app is outdated, using Amazon's new CORS feature the workarounds here are not needed and the uploader can be simplified a lot. The code here is not maintained anymore.

The s3_direct_upload option allows you to pass through arbitrary data. Just check the Options section in the readme.

**Comment by jimmytidey** [comment]
Hey Ncri, 

Thanks for your response, am I correct in thinking this will only work on newer browsers? Doesn't seem to be mentioned on the github page...

Thanks also for the library, it's very helpful!

**Comment by ncri** [comment]
There should be fallbacks for older browsers, but I haven't tested that much.
