### ISSUE TITLE
Getting this error while executing bundle exec rake uploader:deploy

### ISSUE THREAD

**Issue by ratneshnavlakhe** [ncri/s3_uploader_example#22]
Getting this error while executing `bundle exec rake uploader:deploy`

`AWS::S3::PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

Please help..

**Comment by ncri** [comment]
Hi there, i don't support this code anymore it's very old, try out github.com/waynehoover/s3_direct_upload as i recommend in the readme.
