### ISSUE TITLE
Timeout error from s3 when uploading big files

### ISSUE THREAD

**Issue by jhjwind** [ncri/s3_uploader_example#3]
Once every while I got this error message from s3. It happens a lot when I upload big files(>150mb).

<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message>

**Comment by ncri** [comment]
Sorry for the late answer. It seems Amazon stops receiving files from the uploader in those cases, which times out when there is no data coming for 20 secs (see https://forums.aws.amazon.com/message.jspa?messageID=215367). Could it be a network issue? Maybe your connection is instable at times?

**Comment by jhjwind** [comment]
Thanks for you reply.. I think it's a network issue... I tried a bunch of uploaders, even route through nginx.. none of them helps with the network problem... 

The problem happens a lot when I upload a big file...
