### ISSUE TITLE
setting the environment variables

### ISSUE THREAD

**Issue by tstat** [ncri/s3_uploader_example#4]
Hey, I'm fairly new to ruby on rails and this may be a very elementary question, but I am not sure where to set the environment variables. I have had a little trouble googling about environment variables and would love for you to tell me where to specify the values for these variables. Thank you.

**Comment by ncri** [comment]
Environment variables are set in your operating system. On my MacBook I have them inside ~/.profile like so:

```
export S3_UPLOADER_BUCKET=my_bucket
export S3_UPLOADER_ACCESS_KEY=my_access_key
export S3_UPLOADER_SECRET_ACCESS_KEY=my_secret_access_key
```

I think there are also other places where you can put them. Just google for how to best set environment variable in your operating system, there is plenty of info out there.
