### ISSUE TITLE
Fallback for HTML4?

### ISSUE THREAD

**Issue by krzkrzkrz** [ncri/s3_uploader_example#6]
I tried your app against a browser with no HTML5 support (Firefox 3.0.18). It doesn't seem to fallback to HTML 4. I am able to select a file in the File dialogue, but nothing else happens. 

I checked S3, to see if the file was uploaded, but nothing.

Is this the intended behaviour?

**Comment by ncri** [comment]
I haven't tried the app in that old browsers. ;-) Firefox 3 is basically dead, it's not used anymore. However, if supporting it is a requirement for you, you are welcome to investigate what goes wrong, make a fix and send a a pull request to fix it. ;-)
