### ISSUE TITLE
Am I using html5?

### ISSUE THREAD

**Issue by alecguintu** [ncri/s3_uploader_example#8]
Hi Nico,

This is not an actual issue but a question and clarification.

I am wondering what makes the code/project HTML5? Or is this pure HTML4? I am not using the `<progress>` and changed it to div so I think that one's in html4 already.

I checked and used this project and already made changes so that it would work with my system and workflow. I can paste fragments of my code if you'll need it.

**Comment by ncri** [comment]
Well the progress element is html5, yes. But I think you are right, that's about it.
