### ISSUE TITLE
How to enable multiple hosts?

### ISSUE THREAD

**Issue by krzkrzkrz** [ncri/s3_uploader_example#9]
In `s3_uploader.js`, there is:

```
var host = 'http://foobar.com';
```

How does one set this up with multiple protocols? For example: `http://www.foobar.com` and `http://.foobar.com`.

Apparently, the uploader does not work, if `var host = 'http://foobar.com';` and one uploads from `http://www.foobar.com`.

Any ideas?

**Comment by ncri** [comment]
In general one should avoid multiple hosts for seo reasons. It's good to decide for using www or not and then always redirect. So e.g. if the user types  www.yourdomain.com you redirect to yourdomain.com. 

Anyway, If you absolutely want to have both domains, you need to set the javascript host variable separately, depending on which domain the user is on. But as I said, from my experience supporting www and non-www at the same time is not a good idea.

**Comment by gugl** [comment]
To solve this, I'm setting the host as query parameter within the iframe src url and use it from within the template.

**Comment by ncri** [comment]
Good idea, although using www. and non www domains at the same time is not. ;-)
